[build]
target = "index.html"
dist = "dist"
filehash = false

[watch]
watch = ["src"]
ignore = ["node_modules"]

[[hooks]]
stage = "build"
command = "sh"
command_arguments = [
    "-c",
    "pnpm cross-env NODE_ENV=production postcss src/styles/main.css -o $TRUNK_STAGING_DIR/tailwind.css --minify"
]
